CREATE DATABASE groupomania_socialnetwork;
USE groupomania_socialnetwork;

CREATE TABLE User ( id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
admin BOOLEAN DEFAULT FALSE,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
user_password VARCHAR(255) NOT NULL
);

CREATE TABLE Post ( id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(500),
comment_post VARCHAR(500),
like_count INTEGER DEFAULT NULL
);

CREATE TABLE Image ( id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(100)
);

CREATE TABLE Comment ( id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(500) NOT NULL
);
